In [ ]:
!pip install torch


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 99.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 84.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 53.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 65.1 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [ ]:
!pip install matplotlib

In [ ]:
!pip install sklearn.model selection

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for selection: filename=selection-0.0.21-py3-none-any.whl size=9147 sha256=b45d955493646447bb235ff92ce8fc2101e22f5c58bff3aa54073bfa17a7d41d
  Stored in directory: /root/.cache/pip/wheels/82/b0/53/81b3475cc32d4566a1163df1ba51ceb4c8aa9e33f46f2c3094
Successfully built selection


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


#
df = pd.read_csv("/Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
#Generated code may be subject to a license | KaustubhPatil-DS/KaustubhPatil-DS
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
le = LabelEncoder()
X = df. drop(["Species" ], axis = 1). values
y = le. fit_transform(df ["Species"]. values)
# chia dữ liệu với test size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train = torch. FloatTensor(X_train)
X_test = torch. FloatTensor(X_test)
y_train = torch.LongTensor(y_train) .reshape(-1,1)
y_test = torch.LongTensor(y_test) .reshape(-1,1)

print(f"train size {len(y_train)}")

labels, counts = y_train.unique(return_counts=True)
print (labels, counts)

train size 120
tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
import torch

# Tạo một tensor với requirment_grad được đặt thành True

x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

# Đình nghĩa hàm
y = 2 * x ** 4 + x ** 3 + 3 * x ** 2 + 5 * x + 1
print (y)

y.grad_fn

# Thực hiện truyền ngược và tính toán các gradient

y.backward()

# Kết quả đạo hàm

x.grad

tensor(2., requires_grad=True)
None
tensor(63., grad_fn=<AddBackward0>)


tensor(93.)

In [ ]:
# BÀI TẬP
# Cho y = 5x^6 + 3x^3 + 2x^1 + x + 2x + 5x^4+1
# Cho biết độ dốc của đa thức trên tại điểm nào
from sympy import symbols, diff

# Khai báo biến và hàm số
x = symbols('x')
y = 5*x**6 + 5*x**4 + 3*x**3 + 4*x + 1

# Tính đạo hàm của hàm số y theo biến x
dy_dx = diff(y, x)
print("Đạo hàm của hàm số là:", dy_dx)

# Tính độ dốc tại một điểm cụ thể (ví dụ: x = 2)
point = 2
slope_at_point = dy_dx.subs(x, point)
print(f"Độ dốc của hàm số tại x = {point} là: {slope_at_point}")


Đạo hàm của hàm số là: 30*x**5 + 20*x**3 + 9*x**2 + 4
Độ dốc của hàm số tại x = 2 là: 1160


In [ ]:
#BTVN 1:
#Tạo một tensor có gia trị ban đầu là 2.0
#Định nghĩa hàm số và tính gradient
#y = x^3 +2x^2 +5x + 1
#hãy tính dy/dx tại giá trị của x
#Dùng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp


import torch

# Tạo một tensor có giá trị ban đầu là 2.0 và yêu cầu tính gradient
x = torch.tensor([2.0], requires_grad=True)

# Định nghĩa hàm số
y = x**3 + 2*x**2 + 5*x + 1

# Tính gradient
y.backward()
print(f"Giá trị của dy/dx tại x = {x.item()} là: {x.grad.item()}")

# Gradient Descent
learning_rate = 0.1
for i in range(10):
    x.grad.zero_()  # Đặt gradient về 0 trước khi tính toán lại
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()  # Tính gradient
    with torch.no_grad():
        x -= learning_rate * x.grad  # Cập nhật giá trị của x
    print(f"Vòng lặp {i+1}: x = {x.item()}, dy/dx = {x.grad.item()}")


Giá trị của dy/dx tại x = 2.0 là: 25.0
Vòng lặp 1: x = -0.5, dy/dx = 25.0
Vòng lặp 2: x = -0.875, dy/dx = 3.75
Vòng lặp 3: x = -1.2546875476837158, dy/dx = 3.796875
Vòng lặp 4: x = -1.7250847816467285, dy/dx = 4.703972339630127
Vòng lặp 5: x = -2.427826166152954, dy/dx = 7.027413368225098
Vòng lặp 6: x = -3.7249975204467773, dy/dx = 12.971714973449707
Vòng lặp 7: x = -6.897680282592773, dy/dx = 31.726829528808594
Vòng lặp 8: x = -18.912006378173828, dy/dx = 120.14325714111328
Vòng lặp 9: x = -119.14640808105469, dy/dx = 1002.3439331054688
Vòng lặp 10: x = -4330.74755859375, dy/dx = 42116.01171875


In [ ]:
## BTVN 2:


Tạo một tập dữ liệu giả lập với x là số giờ học( ngẫu nhiên từ 1 - 10) và y là số điểm được tính theo công thức y =
3x + 5+ noise
Với noise là một giá trị ngẫu nhiên nhỏ
1. Khởi tạo tham số w và b ngẫu nhiên với requires _grad= true
2. tính MSE
3. Tính gradient
4. Cập nhật tham số w và b bằng gradient Descent với Learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình



In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# 1. Tạo tập dữ liệu giả lập
np.random.seed(42)
torch.manual_seed(42)

# Số giờ học (x) từ 1 đến 10
x = torch.randint(1, 11, (100, 1), dtype=torch.float32)

# Số điểm (y) theo công thức y = 3x + 5 + noise
noise = torch.randn(100, 1) * 1.5  # noise nhỏ
y = 3 * x + 5 + noise

# 2. Khởi tạo tham số w và b ngẫu nhiên với requires_grad=True
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# 3. Định nghĩa hàm MSE (Mean Squared Error)
def mse_loss(y_pred, y_true):
    return ((y_pred - y_true) ** 2).mean()

# 4. Định nghĩa optimizer (SGD với learning rate 0.01)
optimizer = optim.SGD([w, b], lr=0.01)

# 5. Huấn luyện mô hình trong 100 vòng lặp
for epoch in range(100):
    # Dự đoán y
    y_pred = w * x + b

    # Tính loss
    loss = mse_loss(y_pred, y)

    # Tính gradient
    loss.backward()

    # Cập nhật tham số w và b bằng gradient descent
    optimizer.step()

    # Đặt gradient về 0 cho lần lặp tiếp theo
    optimizer.zero_grad()

    # In kết quả sau mỗi 10 vòng lặp
    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/100], Loss: {loss.item():.4f}, w: {w.item():.4f}, b: {b.item():.4f}')

# Kết quả cuối cùng
print(f'Final w: {w.item():.4f}, Final b: {b.item():.4f}')

# BTVN 3: Giải thích lý do tại sao cho 2 trường hợp trên
1. Khi sử dụng torch.from_numpy():
- Tensor được tạo ra sẽ chia sẻ bộ nhớ với mảng NumPy gốc.
- Bất kỳ thay đổi nào trên mảng NumPy sẽ phản ánh ngay lập tức lên tensor và ngược lại.
2. Khi sử dụng torch.tensor():
- Tensor được tạo ra là một bản sao độc lập của dữ liệu từ mảng NumPy.
- Vì vậy, thay đổi mảng NumPy gốc sẽ không ảnh hưởng đến tensor được tạo ra bằng phương thức này.

# BTVN 4: bạn hãy giúp thầy về nhà tạo tensor với:
 Empyty
 Zeros
 Ones
 Random
Reshape với view và view as

In [1]:
import torch

# Tạo tensor rỗng với kích thước (2, 3)
empty_tensor = torch.empty(2, 3)
print("Empty Tensor:\n", empty_tensor)
# Tạo tensor chứa toàn số 0 với kích thước (2, 3)
zeros_tensor = torch.zeros(2, 3)
print("Zeros Tensor:\n", zeros_tensor)
# Tạo tensor chứa toàn số 1 với kích thước (2, 3)
ones_tensor = torch.ones(2, 3)
print("Ones Tensor:\n", ones_tensor)
# Tạo tensor ngẫu nhiên với kích thước (2, 3)
random_tensor = torch.rand(2, 3)
print("Random Tensor:\n", random_tensor)
# Tạo một tensor có kích thước (2, 3)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape tensor thành kích thước (3, 2)
reshaped_tensor = tensor.view(3, 2)
print("Reshaped Tensor with view:\n", reshaped_tensor)
# Tạo một tensor khác với kích thước (3, 2)
other_tensor = torch.rand(3, 2)

# Reshape tensor ban đầu thành cùng kích thước với other_tensor
reshaped_tensor_as = tensor.view_as(other_tensor)
print("Reshaped Tensor with view_as:\n", reshaped_tensor_as)

Empty Tensor:
 tensor([[-1.7712e-37,  4.5011e-41, -1.7713e-37],
        [ 4.5011e-41, -1.7715e-37,  4.5011e-41]])
Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random Tensor:
 tensor([[0.2987, 0.5150, 0.7417],
        [0.8984, 0.1787, 0.0232]])
Reshaped Tensor with view:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
Reshaped Tensor with view_as:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
